
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_APP_ACCESS_TOKEN = ''
TWITTER_APP_ACCESS_TOKEN_SECRET = ''

JS_LIB_DIR = '/js/libmin'
JS_DIR = '/js'
CSS_DIR = '/css'

REDIS_DB = 2
TEST_REDIS_DB = 1

from local_settings import *
